#! /bin/bash

set -x
set -euo pipefail

tmpdir=$(mktemp -d /tmp/"$(basename "$0")".XXXXXX)

runTests() {
    env -u GIT_DIR \
        ./Commands/RunTests \
        -IDEClonedSourcePackagesDirPathOverride=~/.pre-push/XcodeClonedSourcePackages \
        "$@"
}

# shellcheck disable=SC2162
while read _ commit _ _; do
    if [ z"${PRE_PUSH_COMMIT_DIR:-}" != z"" ]; then
        rm -rf "$PRE_PUSH_COMMIT_DIR"
        commitDir="$PRE_PUSH_COMMIT_DIR"
    else
        commitDir="$tmpdir/$commit"
    fi
    mkdir "$commitDir"

    git archive-all "$commit" > "$tmpdir/archive-$commit.tar"
    cat "$tmpdir/archive-$commit.tar" | tar -x -C "$commitDir"

    (cd "$commitDir" && ./Commands/PrepareTests)

    testsLog="$tmpdir/$commit-Tests.log"
    testsErrorLog="$tmpdir/$commit-Tests-error.log"
    snapshotsLog="$tmpdir/$commit-Snapshots.log"
    snapshotsErrorLog="$tmpdir/$commit-Snapshots-error.log"

    trap 'cat "$snapshotsErrorLog" "$testsErrorLog" > /dev/stderr' EXIT

    testsBuildDir="${PRE_PUSH_DERIVED_DATA_PATH:-DerivedData}-Tests"
    (cd "$commitDir" && runTests -scheme 'TMBuddyTests' -derivedDataPath "$testsBuildDir" -IDECustomBuildProductsPath="" -IDECustomBuildIntermediatesPath="") > "$testsLog" 2> "$testsErrorLog" &
    testsPid=$!

    snapshotsBuildDir="${PRE_PUSH_DERIVED_DATA_PATH:-DerivedData}-Snapshots"
    (cd "$commitDir" && runTests -scheme 'TMBuddySnapshots' -derivedDataPath "$snapshotsBuildDir" -IDECustomBuildProductsPath="" -IDECustomBuildIntermediatesPath="") > "$snapshotsLog" 2> "$snapshotsErrorLog" &
    snapshotsPid=$!

    wait $snapshotsPid
    wait $testsPid
done
