targets:

  TMBuddy:
    type: application
    platform: macOS
    deploymentTarget: "10.15"
    sources:
      - Targets/TMBuddy
      - Targets/TMBuddyShared
      - Targets/OtherModules
    settings:
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_FILE: Targets/TMBuddy/Bundle/Info.plist
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_NSMainStoryboardFile: Main
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      CODE_SIGN_ENTITLEMENTS: Targets/TMBuddy/Bundle/TMBuddy.entitlements
    scheme:
      commandLineArguments:
        "-enableDump YES": true
        "-suppressNSLog YES": true
        "-forceAppStoreLikeWindowTitle YES": false
    dependencies:
      - target: TMBuddyFinder
  
  TMBuddyFinder:
    type: app-extension
    platform: macOS
    deploymentTarget: "10.15"
    scheme: {}
    sources:
      - Targets/TMBuddyFinder
      - Targets/TMBuddyShared
      - Targets/OtherModules
    settings:
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_FILE: Targets/TMBuddyFinder/Bundle/Info.plist
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_CFBundleDisplayName: TMBuddy
      CODE_SIGN_ENTITLEMENTS: Targets/TMBuddyFinder/Bundle/TMBuddyFinder.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: com.grigorye.TMBuddy.Finder
  
  TMBuddyTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "10.15"
    scheme:
      testTargets:
        - TMBuddyTests
    sources:
      - Targets/TMBuddyTests
      - Targets/TMBuddyShared
      - Targets/OtherModules
      - path: Targets/TMBuddy/Sources
        excludes:
          - Main
      - path: Targets/TMBuddyFinder/Sources
        excludes:
          - Main

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "$(BUNDLE_VERSION)"
  GENERATE_INFOPLIST_FILE: YES
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: 5BV57B67TB

configFiles:
  Debug: XCConfigs/Default.xcconfig
  Release: XCConfigs/Default.xcconfig

name: TMBuddy
options:
  bundleIdPrefix: com.grigorye
  xcodeVersion: 13.2.1
