targets:

  TMBuddy:
    type: application
    platform: macOS
    deploymentTarget: "10.15"
    sources:
      - Targets/TMBuddy/Sources
      - Targets/TMBuddy/Resources
      - Targets/TMBuddyShared
      - Targets/OtherModules
      - path: Targets/TMBuddyFinder/Sources
        excludes: Main
    settings:
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_FILE: Targets/TMBuddy/Bundle/Info-$(GE_INFOPLIST_KIND).plist
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_NSMainStoryboardFile: Main
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      CODE_SIGN_ENTITLEMENTS: Targets/TMBuddy/Bundle/TMBuddy.entitlements
      OTHER_LDFLAGS: -ObjC
    scheme:
      commandLineArguments:
        "-enableDump YES": true
        "-suppressNSLog YES": true
        "-suppressErrorReporting YES": true
        "-forceAppStoreLikeWindowTitle YES": false
        "-forceFakeFailureOnExcludeByPath YES": false
        "-debug YES": false
        "-debug NO": true
        "-debugAlienPlugin YES": false
        "-debugAlienPrivilegedHelper YES": false
        "-FIRDebugEnabled YES": false
    dependencies:
      - target: TMBuddyFinder
      - target: TMBuddyTMUtilHelper
        embed: true
        copy:
          destination: wrapper
          subpath: Contents/Library/LaunchServices
      - package: Blessed
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
  
  TMBuddyFinder:
    type: app-extension
    platform: macOS
    deploymentTarget: "10.15"
    scheme: {}
    sources:
      - Targets/TMBuddyFinder
      - Targets/TMBuddyShared
      - Targets/OtherModules
    settings:
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_FILE: Targets/TMBuddyFinder/Bundle/Info.plist
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_CFBundleDisplayName: TMBuddy
      CODE_SIGN_ENTITLEMENTS: Targets/TMBuddyFinder/Bundle/TMBuddyFinder.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: com.grigorye.TMBuddy.Finder
      OTHER_LDFLAGS: -ObjC
    dependencies:
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseAnalytics
    
  TMBuddyTMUtilHelper:
    type: tool
    platform: macOS
    deploymentTarget: "10.15"
    scheme: {}
    sources:
      - Targets/TMBuddyTMUtilHelper
      - Targets/TMBuddyFinder/Sources/Helpers/TMUtil/TMUtilLauncher.swift
      - Targets/OtherModules/Tracing.swift
      - Targets/OtherModules/ErrorTracing.swift
      - Targets/OtherModules/XPC
      - Targets/OtherModules/SourceLevel
      - path: Targets/OtherModules/ErrorReporting
        excludes:
          - CrashlyticsErrorReporter.swift
      - Targets/OtherModules/CallStack.swift
      - Targets/OtherModules/Array+URLPaths.swift
      - Targets/OtherModules/Launching.swift
      - Targets/OtherModules/Sugar.swift
      - Targets/OtherModules/UserDefaults+DefaultsKey.swift
      - Targets/TMBuddyShared/XPC/TMUtilHelperXPC.swift
      - Targets/TMBuddyShared/XPC/CommonHelperXPC.swift
      - Targets/TMBuddyShared/Globals
      - Targets/TMBuddyShared/Data/DefaultsKey.swift
      - Targets/TMBuddyShared/Data/PlugInHostConnectionVersion.swift
    settings:
      SKIP_INSTALL: YES
      PRODUCT_NAME: com.grigorye.TMBuddy.TMUtilHelper
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_FILE: Targets/TMBuddyTMUtilHelper/Bundle/Info-$(GE_INFOPLIST_KIND).plist
      PRODUCT_BUNDLE_IDENTIFIER: com.grigorye.TMBuddy.TMUtilHelper
      INFOPLIST_PREPROCESS: YES
      INFOPLIST_PREPROCESSOR_DEFINITIONS: BUNDLE_VERSION=$(BUNDLE_VERSION)
      CREATE_INFOPLIST_SECTION_IN_BINARY: YES
      OTHER_LDFLAGS: -sectcreate __TEXT __launchd_plist Targets/TMBuddyTMUtilHelper/Bundle/launchd.plist
      LD_RUNPATH_SEARCH_PATHS:
        - $(inherited)
        - /usr/local/lib/TMBuddy/Frameworks

  TMBuddyTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "10.15"
    scheme:
      testTargets:
        - TMBuddyTests
    sources:
      - Targets/TMBuddyTests
      - Targets/TMBuddyShared
      - Targets/OtherModules
      - path: Targets/TMBuddy/Sources
        excludes:
          - Main
      - path: Targets/TMBuddyFinder/Sources
        excludes:
          - Main
    dependencies:
      - package: Blessed

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: '8.0'
  Blessed:
    url: https://github.com/trilemma-dev/Blessed
    from: '0.0.1'

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "$(BUNDLE_VERSION)"
  GENERATE_INFOPLIST_FILE: YES
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: 5BV57B67TB

configFiles:
  Debug: XCConfigs/Default.xcconfig
  Release: XCConfigs/Default.xcconfig

name: TMBuddy
options:
  bundleIdPrefix: com.grigorye
  xcodeVersion: 13.2.1
