#! /bin/bash

[ "${RUNNER_DEBUG:-}" == "1" ] && set -x

set -euo pipefail

case "$TESTS_SCHEME" in
TMBuddySnapshots)
    find Targets -path '**+Snapshots/**/*.png'
    ;;
TMBuddyUITestSnapshots)
    find Targets -path '**+UITestSnapshots/**/*.png'
    ;;
*)
    exit 1
    ;;
esac
