#! /bin/bash

scheme="$1" # e.g. "TMBuddyTests"
shift
xcresult="$1" # e.g. /tmp/Tests.seyMey/TMBuddyTests.xcresult
shift

# shellcheck source=../Commands/Xcodebuild-env.sh
. ./Commands/Xcodebuild-env.sh

testExitCode=0
xcodebuild \
    test \
    -project Xcodeproj/*-"$PROJECT_KIND".xcodeproj \
    -derivedDataPath "$DERIVED_DATA_PATH" \
    -disableAutomaticPackageResolution \
    -scheme "$scheme" \
    -resultBundlePath "$xcresult" |
    xcpretty ||
    testExitCode=${PIPESTATUS[0]}
echo "$testExitCode" > "${xcresult/%.xcresult/.exit-code}"
./GHAShortcuts/gh-tar "$(dirname "$xcresult")" "$xcresult"
exit "$testExitCode"
