#! /bin/bash

set -x
set -euo pipefail

provisioningDir="$1"; shift
casksDir="$1"; shift

lastRun=$(Publishing/LastRun)

gh run watch "$lastRun" --exit-status

Publishing/DownloadAndPublish "$lastRun" "$provisioningDir" "$casksDir"

(cd "$casksDir" && git commit -m "Updated TMBuddy." time-machine-buddy.rb && git push)

/opt/homebrew/bin/brew upgrade
