#! /bin/bash

set -x
set -euo pipefail

xcodegen -s XcodeGen/Variant/ExportLocalizations.yml -r . -p Xcodeproj

xcodebuild \
    -exportLocalizations \
    -project Xcodeproj/TMBuddy-ExportLocalizations.xcodeproj \
    -localizationPath Localizations/Exported \
    -exportLanguage en \
    -exportLanguage ru \
    -exportLanguage ca
