#! /bin/bash

set -x
set -euo pipefail

enabled="$1"; shift

defaults write com.grigorye.TMBuddy debug -bool "$enabled"
defaults write com.grigorye.TMBuddy.Finder debug -bool "$enabled"
defaults write com.grigorye.TMBuddy.Finder FIRDebugEnabled -bool "$enabled"
