#! /bin/bash

set -x
set -euo pipefail

xcodegen -s XcodeGen/Variant/ExportLocalizations.yml -r . -p .

xcodebuild \
    -importLocalizations \
    -project TMBuddy-ExportLocalizations.xcodeproj \
    -localizationPath phrase/pull/ru.xlf
