#! /bin/bash

set -x
set -euo pipefail

xcodegen -s XcodeGen/Variant/ExportLocalizations.yml -r . -p .

for lang in ru en; do
    xcodebuild \
        -importLocalizations \
        -project TMBuddy-ExportLocalizations.xcodeproj \
        -localizationPath Localizations/Pulled/"$lang".xliff
done
