#! /bin/bash

set -x
set -euo pipefail

sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db \
    'select client from access where auth_value and service = "kTCCServiceSystemPolicyAllFiles"'
