#! /bin/bash

set -x
set -euo pipefail

wd=$(dirname "$0")

. "$wd"/Xcodebuild-env.sh

tmpdir=$(mktemp -d /tmp/"$(basename "$0")".XXXXXX)

xcodebuildProject() {
    xcodebuild \
        -project Xcodeproj/*-DeveloperID.xcodeproj \
        -disableAutomaticPackageResolution \
        "$@"
}

time xcodebuildProject build-for-testing "$@" |
    tee "$tmpdir/xcodebuild.build-for-testing.log" |
    xcpretty

time xcodebuildProject test-without-building -parallel-testing-enabled YES "$@" |
    tee "$tmpdir/xcodebuild.test-without-building.log" |
    xcpretty
