#! /bin/bash

set -x
set -euo pipefail

tmpdir=$(mktemp -d /tmp/"$(basename "$0")".XXXXXX)

xcodebuild() {
    command xcodebuild \
        -project Xcodeproj/*-DeveloperID.xcodeproj \
        -disableAutomaticPackageResolution \
        "$@"
}

xcpretty() {
    if [ "${XCPRETTY_ENABLED:-}" != "NO" ] && which xcpretty > /dev/null; then
        command xcpretty
    else
        grep -v '^ '
    fi
}

time xcodebuild build-for-testing "$@" |
    tee "$tmpdir/xcodebuild.build-for-testing.log" |
    xcpretty

time xcodebuild test-without-building -parallel-testing-enabled YES "$@" |
    tee "$tmpdir/xcodebuild.test-without-building.log" |
    xcpretty
