#! /bin/bash

set -x
set -euo pipefail

devExtra="$1"; shift

service="com.gentin${devExtra:-}.TMBuddy.TMUtilHelper"

sudo launchctl remove "$service" || true
sudo rm -v /Library/LaunchDaemons/"$service".plist
sudo rm -v /Library/PrivilegedHelperTools/"$service"
