#! /bin/bash

set -x
set -euo pipefail

for projectKindSuffix in "" -Full -Compact -AppStore -DeveloperID; do
    xcodegen -s project"$projectKindSuffix".yml
    xcodebuild -resolvePackageDependencies -project "TMBuddy$projectKindSuffix.xcodeproj"
done
