#! /bin/bash

set -x
set -euo pipefail

for projectVariant in Default AppStore DeveloperID ExportLocalizations; do
    xcodegen -s XcodeGen/Variant/"$projectVariant".yml -r . -p .
done

for i in TMBuddy-*.xcodeproj; do
    xcodebuild -resolvePackageDependencies -project "$i"
done
