#! /bin/bash

set -x
set -euo pipefail

for projectVariant in Default AppStore DeveloperID ExportLocalizations Compact-Distribution-Local Full-Local; do
    xcodegen -s XcodeGen/Variant/"$projectVariant".yml -r . -p Xcodeproj
done

for i in Xcodeproj/*.xcodeproj; do
    xcodebuild -resolvePackageDependencies -project "$i"
done
