#! /bin/bash

set -x
set -euo pipefail

runnerCount="$1" # e.g. 4
shift
runnerNamePrefix="$1" # e.g. "tm-buddy-runner-"
shift

wd="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >& /dev/null && pwd)"

for i in $(seq "$runnerCount"); do
    user="$runnerNamePrefix$i"
    "$wd"/DeactivateRunner "$user"
done
