#! /bin/bash

set -x
set -euo pipefail

secretName="$1" # e.g. TM-Buddy-Runner
shift

password=$(pwgen -s 12 1 -1 -y)

# Beware that all XXXSharedRunnerPassword scripts should be kept in sync re: config below.
security add-generic-password -T "" -a "$secretName" -s ACT-Runner -w "$password"
