#! /bin/bash

set -x
set -euo pipefail

secretName="$1" # e.g. TM-Buddy-Runner
shift

# Beware that all XXXSharedRunnerPassword scripts should be kept in sync re: config below.
security find-generic-password -a "$secretName" -s ACT-Runner -w
