#! /bin/bash

set -x
set -euo pipefail

secretName="$1" # e.g. TM-Buddy-Shared
shift

# Beware that all XXXSharedRunnerPassword scripts should be kept in sync re: config below.
security delete-generic-password -a "$secretName" -s ACT-Runner
