#! /bin/bash

set -x
set -euo pipefail
shopt -s nullglob

lastRun="$1"; shift
secretsDir="$1"; shift
casksDir="$1"; shift

bn=$(basename "$0")
tmpdir=$(mktemp -d /tmp/"$bn".XXXXXX)

bundleID="com.gentin.TMBuddy"
bucket="tmbuddy"
formulaName="time-machine-buddy"
appName="TMBuddy"

for buildKind in DeveloperID AppStore; do
    if gh run download "$lastRun" --name "xcarchive-$buildKind" --dir "$tmpdir"/"$buildKind"; then
        tar -xf "$tmpdir"/"$buildKind"/*.xcarchive.tar -C "$tmpdir"/"$buildKind"
        ./Publishing/UploadDSymsToCrashlytics "$tmpdir"/"$buildKind"/*.xcarchive
    fi
done

./Publishing/DownloadDmg "$lastRun" "$tmpdir"/dmg

dmgs=("$tmpdir"/dmg/*.dmg)
dmg="${dmgs[0]}"
dmgBasename=$(basename "$dmg")
version=$(echo "$dmgBasename" | cut -d '-' -f 2 | sed -e 's/\.dmg$//')

./Publishing/NotarizeDmg "$tmpdir"/dmg/*.dmg "$tmpdir"/notarized "$secretsDir" "$bundleID"

publishedUrl=$(./Publishing/PublishDmg "$tmpdir"/notarized/*.dmg "$bucket")

./Publishing/GenBrewFormula \
    "$casksDir" \
    "$formulaName" \
    "$appName" \
    "$tmpdir"/notarized/*.dmg \
    "$publishedUrl" \
    "$version"
