#! /bin/bash

set -eu -o pipefail

formulaDir="$1"
shift
formulaName="$1"
shift
appName="$1"
shift
dmg="$1"
shift
dmgUrl="$1"
shift
bundleVersion="$1"
shift

test -d "$formulaDir" || mkdir "$formulaDir"

cat >"$formulaDir/$formulaName.rb" <<END
cask '$formulaName' do
  version '$bundleVersion'
  sha256 '$(shasum -a 256 "$dmg" | cut -d ' ' -f 1)'

  url '$dmgUrl'
  name '$appName'
  homepage 'https://github.com/grigorye/$appName'

  app '$appName.app'
end
END
