#! /bin/bash

set -x
set -euo pipefail

xcarchive="$1"
shift

for target in Targets/*; do
    googleServiceInfoPlist="$target/Resources/GoogleService-Info.plist"
    if [ -f "$googleServiceInfoPlist" ]; then
        upload-symbols \
            -d \
            -p mac \
            -gsp "$googleServiceInfoPlist" \
            "$xcarchive"/dSYMs/*.dSYM
    fi
done
