name: build-app

on:
  push:
    branches:
    - master
    - 'feature/*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}

jobs:
  build:
    name: ${{ matrix.run-config.scheme }}
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - scheme: 'TMBuddy'
            destination: 'generic/platform=macOS'
            exportOptionsPlist: 'dist/appstore-exportOptions.plist'
            uploadType: 'macos'
            packageExtension: '.pkg'
    env:
      APP_STORE_AUTHENTICATION_KEY_BASE64: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_BASE64 }}
      APP_STORE_AUTHENTICATION_KEY_ID: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_ID }}
      APP_STORE_AUTHENTICATION_KEY_ISSUER_ID: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_ISSUER_ID }}
    
    steps:

    - name: Dump Environment
      run: |
        env | sort

    - name: Setup Environment
      run: |
        echo 'ARCHIVE_PATH=${{ runner.temp }}/build.xcarchive' >> $GITHUB_ENV
        echo 'EXPORT_PATH=${{ runner.temp }}/build.export' >> $GITHUB_ENV
        echo 'AUTHENTICATION_KEY_PATH=${{ runner.temp }}/authentication.p8' >> $GITHUB_ENV

    - uses: maxim-lobanov/setup-xcode@v1
      if: ${{ runner.name == 'Hosted Agent' }}
      with:
        xcode-version: '12.4'
    
    - name: Install App Store Connect API Key
      run: |
        echo -n "$APP_STORE_AUTHENTICATION_KEY_BASE64" | base64 --decode --output "$AUTHENTICATION_KEY_PATH"
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Create Keychain
      env:
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        KEYCHAIN_PATH="$RUNNER_TEMP"/app-signing.keychain-db

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
        security list-keychain -d user -s "$KEYCHAIN_PATH"

    - name: Install certificates
      env:
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_BASE64: ${{ secrets.APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_BASE64 }}
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        EXPORT_CERTIFICATE_BASE64: ${{ secrets.EXPORT_CERTIFICATE_BASE64 }}
      run: |
        # create variables
        KEYCHAIN_PATH="$RUNNER_TEMP"/app-signing.keychain-db
        APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_PATH="$RUNNER_TEMP"/apple_wwdr_ca.cer
        BUILD_CERTIFICATE_PATH="$RUNNER_TEMP"/build_certificate.p12
        EXPORT_CERTIFICATE_PATH="$RUNNER_TEMP"/export_certificate.p12

        # import certificate from secrets
        echo -n "$APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_BASE64" | base64 --decode --output "$APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_PATH"
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output "$BUILD_CERTIFICATE_PATH"
        echo -n "$EXPORT_CERTIFICATE_BASE64" | base64 --decode --output "$EXPORT_CERTIFICATE_PATH"

        # import certificate to keychain
        security import "$APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_PATH" -k "$KEYCHAIN_PATH"
        security import "$BUILD_CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
        security import "$EXPORT_CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"

    - name: Erase profiles remaining from previous builds
      run: |
        rm -rf ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Build .xcarchive
      run: |
        # create variables
        BUNDLE_VERSION=$(git log --pretty=format:"%h" | wc -l | awk '{print $1}')

        # build
        xcodebuild archive \
          -archivePath "$ARCHIVE_PATH" \
          -scheme '${{ matrix.run-config.scheme }}' \
          -destination '${{ matrix.run-config.destination }}' \
          -showBuildTimingSummary \
          -allowProvisioningUpdates \
          -authenticationKeyPath "$AUTHENTICATION_KEY_PATH" \
          -authenticationKeyID "$APP_STORE_AUTHENTICATION_KEY_ID" \
          -authenticationKeyIssuerID "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID" \
          BUNDLE_VERSION="$BUNDLE_VERSION"

    - name: Save .xcarchive
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.run-config.scheme }}.xcarchive
        path: |
          ${{ env.ARCHIVE_PATH }}

    - name: Export archive
      run: |
        # create variables
        EXPORT_OPTIONS_PLIST='${{ matrix.run-config.exportOptionsPlist }}'

        # export archive
        xcodebuild \
          -exportArchive \
          -archivePath "$ARCHIVE_PATH" \
          -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
          -exportPath "$EXPORT_PATH" \
          -allowProvisioningUpdates \
          -authenticationKeyPath "$AUTHENTICATION_KEY_PATH" \
          -authenticationKeyID "$APP_STORE_AUTHENTICATION_KEY_ID" \
          -authenticationKeyIssuerID "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID"
          
    - name: Upload to TestFlight
      run: |
        # create variables
        API_KEY_NAME="$APP_STORE_AUTHENTICATION_KEY_ID"
        API_PRIVATE_KEYS_DIR="$RUNNER_TEMP/private_keys"
        EXPORT_PATH="$RUNNER_TEMP"/build.export

        # populate private keys directory
        mkdir -p "$API_PRIVATE_KEYS_DIR"
        echo -n "$APP_STORE_AUTHENTICATION_KEY_BASE64" | base64 --decode --output "$API_PRIVATE_KEYS_DIR/AuthKey_$API_KEY_NAME.p8"

        # upload .ipa
        ls -l "$API_PRIVATE_KEYS_DIR"
        ls -l "$EXPORT_PATH"
        env API_PRIVATE_KEYS_DIR="$API_PRIVATE_KEYS_DIR" \
          xcrun altool \
          --upload-app \
          --type ${{ matrix.run-config.uploadType }} \
          --file "$EXPORT_PATH"/*${{ matrix.run-config.packageExtension }} \
          --apiKey "$API_KEY_NAME" \
          --apiIssuer "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID"
