name: build-app

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  paths-filter:
    name: 'Paths Filter'
    uses: ./.github/workflows/paths-filter.yml

  build-app:
    name: 'App'
    needs: [paths-filter]
    if: github.event_name != 'pull_request' || (github.event.pull_request.draft == false && needs.paths-filter.outputs.should_build == 'true')
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v5
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit

  finalize-build-app:
    name: 'Finalize App Build'
    if: always()
    needs: [paths-filter, build-app]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check required build results'
        if: needs.paths-filter.outputs.should_build != 'false'
        run: |
          [ "${{ needs.build-app.result }}" == "success" ]
      - name: 'Report success for skipped build'
        if: needs.paths-filter.outputs.should_build == 'false'
        run: |
          echo 'No build required.'
