name: build-app

on:
  workflow_dispatch: {}
  pull_request:
    branches: [main]

jobs:
  build-app:
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v1
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit
