name: build-app

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  build-app:
    name: 'App'
    if: github.event.pull_request.draft == false
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v2
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit
