name: build-app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      build-config:
        type: choice
        description: build-config
        options: 
        - app-store
        - developer-id
        required: true

defaults:
  run:
    shell: bash {0}

jobs:
  build-app:
    name: ${{ matrix.run-config.scheme }}-${{ matrix.build-config.name }}
    runs-on: macos-12
    strategy:
      matrix:
        run-config:
          - scheme: 'TMBuddy'
            destination: 'generic/platform=macOS'
            uploadType: 'macos'
            packageExtension: '.pkg'
        build-config:
          - name: 'AppStore'
            if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.build-config == 'app-store' }}
            projectKind: 'AppStore'
            exportOptionsPlist: 'dist/appstore-exportOptions.plist'
          - name: 'DeveloperID'
            if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.build-config == 'developer-id' }}
            projectKind: 'DeveloperID'
            exportOptionsPlist: 'dist/developer-id-exportOptions.plist'

    env:
      APP_STORE_AUTHENTICATION_KEY_BASE64: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_BASE64 }}
      APP_STORE_AUTHENTICATION_KEY_ID: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_ID }}
      APP_STORE_AUTHENTICATION_KEY_ISSUER_ID: ${{ secrets.APP_STORE_AUTHENTICATION_KEY_ISSUER_ID }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      KEYCHAIN_NAME: app-signing.keychain-db

    steps:
      - name: ACT preamble
        if: ${{ env.ACT }}
        shell: /bin/bash --noprofile --norc -x -euo pipefail {0}
        run: |
          ./GHALocal/bin/gh-runner-host-preamble

      - name: Dump GitHub Action Properties
        if: ${{ !env.ACT }}
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.inputs.build-config: ${{ github.event.inputs.build-config }}"

      - uses: actions/checkout@v2
        if: ${{ matrix.build-config.if }}
        with:
          fetch-depth: 0
          submodules: true

      - name: Dump Environment
        if: ${{ matrix.build-config.if }}
        run: |
          env | sort
          git --no-pager log -10 --pretty=format:"%h %ad %an %s"

      - name: Setup Environment
        if: ${{ matrix.build-config.if }}
        run: |
          echo 'PRODUCT_NAME=${{ matrix.run-config.scheme }}' >> $GITHUB_ENV
          echo "DERIVED_DATA_PATH=$RUNNER_TEMP/build.derivedData" >> $GITHUB_ENV
          echo "EXPORT_PATH=$RUNNER_TEMP/build.export" >> $GITHUB_ENV
          echo "AUTHENTICATION_KEY_PATH=$RUNNER_TEMP/authentication.p8" >> $GITHUB_ENV

      - uses: maxim-lobanov/setup-xcode@v1.4.1
        if: ${{ matrix.build-config.if && !env.ACT }}
        with:
          xcode-version: '13.4'

      - name: Install Brew
        if: ${{ matrix.build-config.if && env.ACT }}
        run: |
          ./GHAShortcuts/InstallBrew

      - name: Install Dependencies
        if: ${{ matrix.build-config.if }}
        run: |
          ./GHAShortcuts/InstallDependencies
          ./GHAShortcuts/InstallDependencies-build-app

      - name: Cache Mint packages
        if: ${{ matrix.build-config.if }}
        id: mint-cache
        uses: actions/cache@v2
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Install Mint packages
        if: matrix.build-config.if && steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap

      - name: Install App Store Connect API Key
        if: ${{ matrix.build-config.if }}
        run: |
          echo -n "$APP_STORE_AUTHENTICATION_KEY_BASE64" | base64 --decode --output "$AUTHENTICATION_KEY_PATH"

      - name: Setup Version Dependent Environment
        if: ${{ matrix.build-config.if }}
        run: |
          # Create variables
          BUNDLE_VERSION=$(GHAScripts/BundleVersion)

          echo "BUNDLE_VERSION=$BUNDLE_VERSION" >> $GITHUB_ENV
          echo "PRODUCT_NAME=$PRODUCT_NAME" >> $GITHUB_ENV
          echo "ARCHIVE_PATH=$RUNNER_TEMP/$PRODUCT_NAME-$BUNDLE_VERSION-${{ matrix.build-config.name }}.xcarchive" >> $GITHUB_ENV
          echo "DMG_PATH=$RUNNER_TEMP/$PRODUCT_NAME-$BUNDLE_VERSION.dmg" >> $GITHUB_ENV

      - name: Create Keychain
        if: ${{ matrix.build-config.if }}
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          KEYCHAIN_PATH="$RUNNER_TEMP"/"$KEYCHAIN_NAME"

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security list-keychain -d user -s "$KEYCHAIN_PATH"

      - name: Install certificates
        if: ${{ matrix.build-config.if }}
        env:
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_BASE64: ${{ secrets.APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_BASE64 }}
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          EXPORT_CERTIFICATE_BASE64: ${{ secrets.EXPORT_CERTIFICATE_BASE64 }}
          EXPORT_CERTIFICATE_DEVELOPER_ID_BASE64: ${{ secrets.EXPORT_CERTIFICATE_DEVELOPER_ID_BASE64 }}
        run: |
          # create variables
          KEYCHAIN_PATH="$RUNNER_TEMP"/app-signing.keychain-db
          APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_PATH="$RUNNER_TEMP"/apple_wwdr_ca.cer
          BUILD_CERTIFICATE_PATH="$RUNNER_TEMP"/build_certificate.p12
          EXPORT_CERTIFICATE_PATH="$RUNNER_TEMP"/export_certificate.p12
          EXPORT_CERTIFICATE_DEVELOPER_ID_PATH="$RUNNER_TEMP"/export_certificate_developer_id.p12

          # import certificate from secrets
          echo -n "$APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_BASE64" | base64 --decode --output "$APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_PATH"
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output "$BUILD_CERTIFICATE_PATH"
          echo -n "$EXPORT_CERTIFICATE_BASE64" | base64 --decode --output "$EXPORT_CERTIFICATE_PATH"
          echo -n "$EXPORT_CERTIFICATE_DEVELOPER_ID_BASE64" | base64 --decode --output "$EXPORT_CERTIFICATE_DEVELOPER_ID_PATH"

          # import certificate to keychain
          security import "$APPLE_WWDR_CERTIFICATION_AUTHORITY_CER_PATH" -k "$KEYCHAIN_PATH"
          security import "$BUILD_CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security import "$EXPORT_CERTIFICATE_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security import "$EXPORT_CERTIFICATE_DEVELOPER_ID_PATH" -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"

      - name: Erase profiles remaining from previous builds
        if: ${{ matrix.build-config.if }}
        run: |
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles
      
      - uses: actions/cache@v2
        if: ${{ false && matrix.build-config.if }}
        with:
          path: ${{ env.DERIVED_DATA_PATH }}/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: XcodeGen
        if: ${{ matrix.build-config.if }}
        run: |
          mint run xcodegen -s XcodeGen/Variant/${{ matrix.build-config.projectKind }}.yml -r . -p Xcodeproj

      - name: Build .xcarchive
        if: ${{ matrix.build-config.if }}
        run: |
          # build
          . ./Commands/Xcodebuild-env.sh
          xcodebuild archive \
            -project Xcodeproj/*-${{ matrix.build-config.projectKind }}.xcodeproj \
            -derivedDataPath "$DERIVED_DATA_PATH" \
            -disableAutomaticPackageResolution \
            -archivePath "$ARCHIVE_PATH" \
            -scheme '${{ matrix.run-config.scheme }}' \
            -destination '${{ matrix.run-config.destination }}' \
            -showBuildTimingSummary \
            -allowProvisioningUpdates \
            -authenticationKeyPath "$AUTHENTICATION_KEY_PATH" \
            -authenticationKeyID "$APP_STORE_AUTHENTICATION_KEY_ID" \
            -authenticationKeyIssuerID "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID" \
            BUNDLE_VERSION="$BUNDLE_VERSION" \
            | xcpretty
          ./GHAShortcuts/gh-tar "$(dirname "$ARCHIVE_PATH")" "$ARCHIVE_PATH"

      - name: Pull .xcarchive
        if: ${{ matrix.build-config.if && env.ACT }}
        shell: bash --noprofile --norc -x -euo pipefail {0}
        run: |
          scp -pr "$REMOTE_RUNNER_USER"@host.docker.internal:"$ARCHIVE_PATH".tar "$ARCHIVE_PATH".tar

      - name: Save .xcarchive
        if: ${{ matrix.build-config.if }}
        uses: actions/upload-artifact@v2
        with:
          name: xcarchive-${{ matrix.build-config.name }}
          if-no-files-found: error
          path: |
            ${{ env.ARCHIVE_PATH }}.tar

      - name: Export archive
        if: ${{ matrix.build-config.if }}
        run: |
          # create variables
          EXPORT_OPTIONS_PLIST='${{ matrix.build-config.exportOptionsPlist }}'

          # export archive
          xcodebuild \
            -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$EXPORT_PATH" \
            -allowProvisioningUpdates \
            -authenticationKeyPath "$AUTHENTICATION_KEY_PATH" \
            -authenticationKeyID "$APP_STORE_AUTHENTICATION_KEY_ID" \
            -authenticationKeyIssuerID "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID"

      - name: Create .dmg
        if: ${{ matrix.build-config.if && matrix.build-config.name == 'DeveloperID' }}
        run: |
          # Create .dmg
          hdiutil create \
              -volname '${{ matrix.run-config.scheme }}' \
              -srcfolder "$EXPORT_PATH" \
              -ov \
              -format UDZO \
              "$DMG_PATH"

      - name: Pull .dmg
        if: ${{ matrix.build-config.if && matrix.build-config.name == 'DeveloperID' && env.ACT }}
        shell: bash --noprofile --norc -x -euo pipefail {0}
        run: |
          scp -pr "$REMOTE_RUNNER_USER"@host.docker.internal:"$DMG_PATH" "$DMG_PATH"
          
      - name: Save .dmg
        if: ${{ matrix.build-config.if && matrix.build-config.name == 'DeveloperID' }}
        uses: actions/upload-artifact@v2
        with:
          name: dmg
          if-no-files-found: error
          path: |
            ${{ env.DMG_PATH }}

      - name: Upload to TestFlight
        if: ${{ matrix.build-config.if && matrix.build-config.name == 'AppStore' && !env.ACT }}
        run: |
          # create variables
          API_KEY_NAME="$APP_STORE_AUTHENTICATION_KEY_ID"
          API_PRIVATE_KEYS_DIR="$RUNNER_TEMP/private_keys"
          EXPORT_PATH="$RUNNER_TEMP"/build.export

          # populate private keys directory
          mkdir -p "$API_PRIVATE_KEYS_DIR"
          echo -n "$APP_STORE_AUTHENTICATION_KEY_BASE64" | base64 --decode --output "$API_PRIVATE_KEYS_DIR/AuthKey_$API_KEY_NAME.p8"

          # upload .ipa
          ls -l "$API_PRIVATE_KEYS_DIR"
          ls -l "$EXPORT_PATH"
          env API_PRIVATE_KEYS_DIR="$API_PRIVATE_KEYS_DIR" \
            xcrun altool \
            --upload-app \
            --type ${{ matrix.run-config.uploadType }} \
            --file "$EXPORT_PATH"/*${{ matrix.run-config.packageExtension }} \
            --apiKey "$API_KEY_NAME" \
            --apiIssuer "$APP_STORE_AUTHENTICATION_KEY_ISSUER_ID"

      - name: ACT epilogue
        if: ${{ env.ACT && always() }}
        shell: /bin/bash --noprofile --norc -x -euo pipefail {0}
        run: |
          ./GHALocal/bin/gh-runner-host-epilogue
