name: main

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  paths-filter:
    name: 'Paths Filter'
    uses: ./.github/workflows/paths-filter.yml
  
  unit-tests:
    name: 'Unit Tests'
    needs: [paths-filter]
    if: github.event.pull_request.draft != true && needs.paths-filter.outputs.should-test != 'false'
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-reusable.yml@v17
    secrets: inherit
    with:
      runs-on: 'macos-12'
      testsScheme: 'TMBuddyTests'
      testsKind: 'UnitTests'
      testsName: 'Unit Tests'

  snapshot-tests:
    name: 'Snapshots'
    needs: [paths-filter]
    if: github.event.pull_request.draft != true && needs.paths-filter.outputs.should-test != 'false'
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-reusable.yml@v17
    secrets: inherit
    with:
      runs-on: 'macos-12'
      testsScheme: 'TMBuddySnapshots'
      testsKind: 'Snapshots'
      testsName: 'Snapshots'

  build-app:
    name: 'App'
    needs: [paths-filter]
    if: github.event.pull_request.draft != true && needs.paths-filter.outputs.should-build != 'false'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v17
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit

  finalize:
    name: 'Finalize Run'
    if: always()
    needs: [paths-filter, snapshot-tests, unit-tests, build-app]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check required build results'
        if: needs.paths-filter.outputs.should-build != 'false'
        run: |
          [ "${{ needs.build-app.result }}" == "success" ]
      - name: 'Check required test results'
        if: needs.paths-filter.outputs.should-test != 'false'
        run: |
          [ "${{ needs.unit-tests.result }}" == "success" ] && [ "${{ needs.unit-tests.outputs.tests-passed }}" == "true" ]
          [ "${{ needs.snapshot-tests.result }}" == "success" ] && [ "${{ needs.snapshot-tests.outputs.tests-passed }}" == "true" ]
      - name: 'Report success for skipped jobs'
        if: needs.paths-filter.outputs.should-test == 'false' && needs.paths-filter.outputs.should-build == 'false'
        run: |
          echo 'No job to do.'
