name: main

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: Skip tests
        required: false
        default: false
        type: boolean
      skip-build-app:
        description: Skip build-app
        required: false
        default: false
        type: boolean
  
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}    

jobs:
  tests-filter:
    name: 'Filter Tests'
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.filter.outputs.should-run }}
    env:
      GH_TOKEN: ${{ secrets.ON_DEMAND_TRIGGER_GH_TOKEN }}
    steps:
      - name: 'Filter'
        id: filter
        run: |
          action="test"
          if ${{ github.event_name != 'pull_request' }}; then
            if ${{ inputs.skip-tests == 'false' }}; then
              should_run=true
            else
              should_run=false
            fi
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
            labels=($(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json labels --jq .labels.[].name))
            if [[ " ${labels[@]} " =~ "ci: $action" ]]; then
              printf -v "should_run" "%s" "true" # https://stackoverflow.com/a/16973754/1859783
            else
              printf -v "should_run" "%s" "false"
            fi
          fi
          echo "should-run=$should_run" >> $GITHUB_OUTPUT

  build-app-filter:
    name: 'Filter Build App'
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.filter.outputs.should-run }}
    env:
      GH_TOKEN: ${{ secrets.ON_DEMAND_TRIGGER_GH_TOKEN }}
    steps:
      - name: 'Filter'
        id: filter
        run: |
          action="build-app"
          if ${{ github.event_name != 'pull_request' }}; then
            if ${{ inputs.skip-build-app == 'false' }}; then
              should_run=true
            else
              should_run=false
            fi
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
            labels=($(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json labels --jq .labels.[].name))
            if [[ " ${labels[@]} " =~ "ci: $action" ]]; then
              printf -v "should_run" "%s" "true" # https://stackoverflow.com/a/16973754/1859783
            else
              printf -v "should_run" "%s" "false"
            fi
          fi
          echo "should-run=$should_run" >> $GITHUB_OUTPUT
        
  paths-filter:
    name: 'Paths Filter'
    uses: ./.github/workflows/paths-filter.yml

  tests:
    name: 'Tests'
    needs: [paths-filter, tests-filter]
    if: ${{ !inputs.skip-tests && github.event.pull_request.draft != true && needs.paths-filter.outputs.should-test != 'false' && needs.tests-filter.outputs.should-run == 'true' }}
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-generic.yml@v20
    secrets: inherit
    with:
      runs-on: 'macos-12'
      unit-tests-scheme: 'TMBuddyTests'
      snapshot-tests-scheme: 'TMBuddySnapshots'
      ui-snapshot-tests-scheme: 'TMBuddyUITestSnapshots'

  build-app:
    name: 'App'
    needs: [paths-filter, build-app-filter]
    if: ${{ !inputs.skip-build-app && github.event.pull_request.draft != true && needs.paths-filter.outputs.should-build != 'false' && needs.build-app-filter.outputs.should-run == 'true' }}
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v20
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit
