name: main

on:
  workflow_dispatch:
    inputs:
      skip-tests:
        description: Skip tests
        required: false
        default: false
        type: boolean
      skip-build-app:
        description: Skip build-app
        required: false
        default: false
        type: boolean
  
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  paths-filter:
    name: 'Paths Filter'
    uses: ./.github/workflows/paths-filter.yml
  
  tests:
    name: 'Tests'
    needs: [paths-filter]
    if: ${{ !inputs.skip-tests && github.event.pull_request.draft != true && needs.paths-filter.outputs.should-test != 'false' }}
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-generic.yml@v20
    secrets: inherit
    with:
      runs-on: 'macos-12'
      unit-tests-scheme: 'TMBuddyTests'
      snapshot-tests-scheme: 'TMBuddySnapshots'
      ui-snapshot-tests-scheme: 'TMBuddyUITestSnapshots'

  build-app:
    name: 'App'
    needs: [paths-filter]
    if: ${{ !inputs.skip-build-app && github.event.pull_request.draft != true && needs.paths-filter.outputs.should-build != 'false' }}
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v20
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit
