name: main

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  paths-filter:
    name: 'Paths Filter'
    uses: ./.github/workflows/paths-filter.yml
  
  tests:
    name: 'Tests'
    needs: [paths-filter]
    if: github.event.pull_request.draft != true && needs.paths-filter.outputs.should-test != 'false'
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    with:
      runs-on: 'macos-12'
      unit-tests-scheme: 'TMBuddyTests'
      snapshot-tests-scheme: 'TMBuddySnapshots'

  build-app:
    name: 'App'
    needs: [paths-filter]
    if: github.event.pull_request.draft != true && needs.paths-filter.outputs.should-build != 'false'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v17
    with:
      macos-app-scheme: 'TMBuddy'
      build-configs: '[\"app-store\", \"developer-id\"]'
    secrets: inherit

  finalize:
    name: 'Finalize Run'
    if: always()
    needs: [paths-filter, tests, build-app]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check required build results'
        if: needs.paths-filter.outputs.should-build != 'false'
        run: |
          [ "${{ needs.build-app.result }}" == "success" ]
      - name: 'Check required test results'
        if: needs.paths-filter.outputs.should-test != 'false'
        run: |
          [ "${{ needs.tests.result }}" == "success" ] && [ "${{ needs.tests.outputs.tests-passed }}" == "true" ]
      - name: 'Report success for skipped jobs'
        if: needs.paths-filter.outputs.should-test == 'false' && needs.paths-filter.outputs.should-build == 'false'
        run: |
          echo 'No job to do.'
