name: paths-filter

on:
  workflow_call:
    outputs:
      should_build:
        description: 'Whether to build or not'
        value: ${{ jobs.paths-filter.outputs.should_build }}

jobs:
  paths-filter:
    name: 'Check Paths'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      should_build: ${{ steps.build_check.outputs.should_build }}
    steps:
      - id: build_check
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v2
        with:
          filters: |
            should_build:
              - '.github/**'
              - 'Brewfile.*'
              - 'Brewfile'
              - 'Commands/**'
              - 'dist/**'
              - 'GHAScripts/**'
              - 'GHAShortcuts/**'
              - 'Mintfile'
              - 'project.yml'
              - 'ReusableWorkflows/**'
              - 'Targets/**'
              - 'ThirdParties/**'
              - 'Xcodegen/**'
              - 'Xcodeproj/**'
