name: tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}

jobs:
  paths-filter:
    name: 'Paths Filter'
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/paths-filter.yml

  tests:
    name: 'Tests'
    needs: [paths-filter]
    if: github.event_name != 'pull_request' || (github.event.pull_request.draft == false && needs.paths-filter.outputs.should_build == 'true')
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-reusable.yml@v5
    secrets: inherit
    with:
      runs-on: 'macos-12'
      allScheme: 'TMBuddyAll'
      testsScheme: 'TMBuddyTests'
      snapshotsScheme: 'TMBuddySnapshots'

  finalize-tests:
    name: 'Finalize Tests'
    if: always()
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: 'Report'
        run: |
          [ "${{ needs.tests.result }}" == "success" ]
