name: tests

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

defaults:
  run:
    shell: bash --noprofile --norc -x -euo pipefail {0}

jobs:
  paths-filter:
    name: 'Paths Filter'
    uses: ./.github/workflows/paths-filter.yml

  tests:
    name: 'Tests'
    needs: [paths-filter]
    if: github.event.pull_request.draft != true && needs.paths-filter.outputs.should-test != 'false'
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-reusable.yml@v17
    secrets: inherit
    with:
      runs-on: 'macos-12'
      allScheme: 'TMBuddyAll'
      testsScheme: 'TMBuddyTests'
      snapshotsScheme: 'TMBuddySnapshots'

  finalize-tests:
    name: 'Finalize Tests'
    if: always()
    needs: [paths-filter, tests]
    runs-on: ubuntu-latest
    steps:
      - name: 'Check required test results'
        if: needs.paths-filter.outputs.should-test != 'false'
        run: |
          [ "${{ needs.tests.result }}" == "success" ] && [ "${{ needs.tests.outputs.all-tests-passed }}" == "true" ]
      - name: 'Report success for skipped tests'
        if: needs.paths-filter.outputs.should-test == 'false'
        run: |
          echo 'No tests required.'
