name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: 'Tests'
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-reusable.yml@main
    secrets: inherit
    with:
      runs-on: 'macos-12'
      allScheme: 'TMBuddyAll'
      testsScheme: 'TMBuddyTests'
      snapshotsScheme: 'TMBuddySnapshots'
