name: tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: 'Tests'
    if: github.event.pull_request.draft == false
    uses: grigorye/ReusableWorkflows/.github/workflows/tests-reusable.yml@v3
    secrets: inherit
    with:
      runs-on: 'macos-12'
      allScheme: 'TMBuddyAll'
      testsScheme: 'TMBuddyTests'
      snapshotsScheme: 'TMBuddySnapshots'
