aggregateTargets:
  TMBuddyAll:
    targets:
      - TMBuddy
      - TMBuddyTests
      - TMBuddySnapshots

targets:
  TMBuddy:
    type: application
    platform: macOS
    templates:
      - TMBuddyIntrinsicsTarget
    sources:
      - path: Targets/TMBuddy/Bundle
        buildPhase: none
      - path: Targets/TMBuddy/Sources
        excludes:
          - "**/*+Snapshots"
          - "**/*+Snapshots.swift"
          - "**/*+SampleView.swift"
          - "**/*+Samples.swift"
          - "**/*+Preview.swift"
          # Excluded for Aspect/Helper.yml:
          - Checkpoints/SMJobBless
          - Checkpoints/PostInstallHelper
      - Targets/TMBuddy/Resources
      - Targets/TMBuddy/Localizations
      - Targets/TMBuddyShared
      - Targets/OtherModules
      - path: Targets/TMBuddyFinder/Sources
        excludes:
          - Main
    settings:
      ENABLE_HARDENED_RUNTIME: YES
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: '$(inherited) $(GE_HELPER_ACTIVE_COMPILATION_CONDITIONS)'
      PRODUCT_MODULE_NAME: $(TARGET_NAME)
      PRODUCT_NAME: $(TARGET_NAME)$(GE_PRODUCT_NAME_EXTRA)
      INFOPLIST_FILE: Targets/TMBuddy/Bundle/Info-$(GE_INFOPLIST_KIND).plist
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_NSMainStoryboardFile: Main
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
      GE_HELPER_BUNDLE_ID: $(GE_BUNDLE_ID_PREFIX).TMBuddy.TMUtilHelper
      INFOPLIST_PREPROCESSOR_DEFINITIONS: >
        BUNDLE_VERSION=$(BUNDLE_VERSION)
        GE_BUNDLE_ID_PREFIX=$(GE_BUNDLE_ID_PREFIX)
        GE_HELPER_BUNDLE_ID=$(GE_HELPER_BUNDLE_ID)
        GE_HELPER_BUNDLE_ID_QUOTED='"$(GE_HELPER_BUNDLE_ID)"'
      INFOPLIST_PREPROCESS: YES
      INFOPLIST_OTHER_PREPROCESSOR_FLAGS: -CC
      CODE_SIGN_ENTITLEMENTS: Targets/TMBuddy/Bundle/TMBuddy$(GE_APP_ENTITLEMENTS_SUFFIX).entitlements
      OTHER_LDFLAGS: -ObjC
    scheme:
      commandLineArguments:
        "-enableDump YES": true
        "-suppressNSLog YES": true
        "-analyticsEnabled YES": false
        "-errorReportingEnabled YES": false
        "-actionTrackingEnabled YES": false
        "-elapsedTimeTrackingEnabled YES": false
        "-activityTrackingEnabled YES": false
        "-forceAppStoreLikeWindowTitle YES": false
        "-fakeFailureOnSetExcludedPrivileged YES": false
        "-forcePostInstallCheckpoint YES": false
        "-debug YES": false
        "-debug NO": true
        "-debugAlienPlugin YES": false
        "-debugAlienPrivilegedHelper YES": false
        "-FIRDebugEnabled YES": false
    dependencies:
      - target: TMBuddyFinder

  TMBuddyFinder:
    type: app-extension
    platform: macOS
    scheme: {}
    templates:
      - TMBuddyIntrinsicsTarget
    sources:
      - Targets/TMBuddyFinder
      - Targets/TMBuddyShared
      - Targets/OtherModules
    settings:
      ENABLE_HARDENED_RUNTIME: YES
      INFOPLIST_FILE: Targets/TMBuddyFinder/Bundle/Info.plist
      INFOPLIST_KEY_NSPrincipalClass: NSApplication
      INFOPLIST_KEY_CFBundleDisplayName: TMBuddy$(GE_PRODUCT_NAME_EXTRA)
      CODE_SIGN_ENTITLEMENTS: Targets/TMBuddyFinder/Bundle/TMBuddyFinder.entitlements
      PRODUCT_BUNDLE_IDENTIFIER: $(GE_BUNDLE_ID_PREFIX).TMBuddy.Finder
      PRODUCT_MODULE_NAME: $(TARGET_NAME)
      PRODUCT_NAME: $(TARGET_NAME)$(GE_PRODUCT_NAME_EXTRA)
      OTHER_LDFLAGS: -ObjC

  TMBuddyTests:
    type: bundle.unit-test
    platform: macOS
    templates:
      - TMBuddyIntrinsicsTarget
    scheme:
      testTargets:
        - TMBuddyTests
    sources:
      - Targets/TMBuddyTests
      - path: Targets/TMBuddyShared
        excludes:
          - AppIntegration
      - path: Targets/OtherModules
        excludes:
          - Firebase
      - path: Targets/TMBuddy/Sources
        includes:
          - "**/Standalone/*+Model.swift"
        excludes:
          - Main
          - "**/*+Snapshots"
          - "**/*+Snapshots.swift"
          - "**/*+SampleView.swift"
          - "**/*+Samples.swift"
          - "**/Standalone"
          - "**/*+Integration.swift"
      - path: Targets/TMBuddyFinder/Sources
        excludes:
          - Main

  TMBuddySnapshots:
    type: bundle.unit-test
    platform: macOS
    templates:
      - TMBuddyIntrinsicsTarget
      - TMBuddyStandaloneViewsTarget
    dependencies:
      - package: SnapshotTesting
      - target: TMBuddySnapshotViews
    sources:
      - path: Targets/TMBuddy/Sources
        includes:
          - "**/*Snapshots.swift"
        excludes:
          - "**/*+Snapshots"
      - Targets/OtherTesting
    settings:
      LOCALIZATION_EXPORT_SUPPORTED: NO

  TMBuddySnapshotViews:
    type: framework
    platform: macOS
    templates:
      - TMBuddyStandaloneViewsTarget
    settings:
      LOCALIZATION_EXPORT_SUPPORTED: NO
      LOCALIZED_STRING_SWIFTUI_SUPPORT: NO

targetTemplates:
  TMBuddyIntrinsicsTarget:
    sources:
      - Targets/TMBuddyIntrinsics
    settings:
      GE_BUNDLE_EXTRAS_PLIST: $(BUILT_PRODUCTS_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/BundleExtras.plist
    preBuildScripts:
      - name: 'Generate bundle extras'
        shell: /bin/bash
        script: |
          set -x
          set -euo pipefail
          /usr/libexec/PlistBuddy -c "Clear dict" "$GE_BUNDLE_EXTRAS_PLIST"
          /usr/libexec/PlistBuddy -c "Add :bundleIDPrefix string $GE_BUNDLE_ID_PREFIX" "$GE_BUNDLE_EXTRAS_PLIST"
          /usr/libexec/PlistBuddy -c "Add :bundleIDExtra string ${GE_BUNDLE_ID_EXTRA:-}" "$GE_BUNDLE_EXTRAS_PLIST"
        outputFiles:
          - $(GE_BUNDLE_EXTRAS_PLIST)

  TMBuddyStandaloneViewsTarget:
    type: framework
    platform: macOS
    sources:
      - path: Targets/TMBuddy/Sources
        includes:
          - "**/*View.swift"
          - "**/Standalone/*.swift"
          - AppGlobals/DisplayNames.swift
          - AppGlobals/PlugInURL.swift
          - AppGlobals/BuildInfo.swift
        excludes:
          - Main
          - "**/*+Snapshots"
          - "**/*+Snapshots.swift"
          - "**/Integration"
      - path: Targets/TMBuddyFinder/Sources
        includes:
          - Main/MenuGenerator.swift
      - path: Targets/TMBuddyShared
        includes:
          - Data/TMStatus*.swift
          - Data/DefaultsKey.swift
          - Data/PlugInHostConnectionVersion.swift
          - Resources
      - path: Targets/OtherModules
        excludes:
          - Firebase

schemes:
  TMBuddySnapshots:
    build:
      targets:
        TMBuddySnapshots: all
    run:
    test:
      environmentVariables:
        - variable: FORCE_RUN_FLAKY_SNAPSHOTS
          value: YES
          isEnabled: false
        - variable: SNAPSHOT_RECORDING
          value: YES
          isEnabled: false
      targets:
        - name: TMBuddySnapshots
          parallelizable: true

packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: "1.9.0"

settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "$(BUNDLE_VERSION)"
  GENERATE_INFOPLIST_FILE: YES
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: 465NA5BW7E
  GE_BUNDLE_ID_PREFIX: com.gentin$(GE_BUNDLE_ID_EXTRA)
  
  # Overridden for CI runs:
  BUNDLE_VERSION: Local
  GE_INFOPLIST_KIND: Development
  GE_BUNDLE_ID_EXTRA: .dev
  GE_PRODUCT_NAME_EXTRA: .dev

options:
  developmentLanguage: ca
  bundleIdPrefix: $(GE_BUNDLE_ID_PREFIX)
  xcodeVersion: 13.2.1
  deploymentTarget:
    macOS: 10.15
  createIntermediateGroups: true
